apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appwebcolor.config.name }}
  labels:
    app: {{ .Values.appwebcolor.name }}
data: 
{{- range .Values.appwebcolor.config.data }}
  {{ .key }}: {{ .value }}
{{- end}}
