apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appwebcolor.name }}
  name: {{ .Values.appwebcolor.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appwebcolor.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appwebcolor.name }}
    spec:
      containers:
      - image: {{ .Values.appwebcolor.container.image }}  
        name: {{ .Values.appwebcolor.name }}
        ports:
        - containerPort: {{ .Values.appwebcolor.container.port }}
        envFrom:
        - configMapRef:
          name: {{ .Values.appwebcolor.config.name }}
