apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appwebcolor.name }}
  labels:
    app: {{ .Values.appwebcolor.name }}
spec:
  type: {{ .Values.appwebcolor.service.type }}
  selector:
    app: {{ .Values.appwebcolor.name }}
  ports:
    - port: {{ .Values.appwebcolor.service.port }}
      targetPort: {{ .Values.appwebcolor.container.port }}
