apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app-webcolor.name }}
  labels: 
    app: {{ .Values.app-webcolor.name }}
spec:
  type: {{ .Values.app-webcolor.service.type }}
  selector:             
    app: {{ .Values.app-webcolor.name }}
  ports:
    - port: {{ .Values.app-webcolor.service.port }}       
      targetPort: {{ .Values.app-webcolor.container.port }}