apiVersion: v1
kind: Service
metadata:
  name: lb-svc-app-webcolor
  labels:
    app: lb-svc-app-webcolor
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: app-webcolor
